- name: setup router
  hosts:
  - router

  roles:
  - { name: sssd, tags: sssd }

  - name: resolvconf
    tags: resolvconf

  - name: nat
    tags: nat
  
  - name: gateway
    tags: gateway

  - name: named
    tags: named

