---
ifaces:  
- name: vtnet1
  value: "172.16.0.1/24"

- name: vtnet2
  value: "172.16.99.1/24"

#dhcpd_conf: dhcpd.conf
#dhcpd_ifaces: "vtnet1 vtnet2 vtnet3"

named_conf: named.conf
named_dir: /usr/local/etc/namedb
named_listen_on: "127.0.0.1; 192.168.122.199; 172.16.0.1; 172.16.99.1;" 

static_routes:
- name: internal1
  dst: 172.16.1.0/24
  gw:   172.16.0.99

- name: internal2
  dst: 172.16.2.0/24
  gw:   172.16.0.99

- name: internal3
  dst: 172.16.3.0/24
  gw:   172.16.0.99

- name: internal4
  dst: 172.16.4.0/24
  gw:   172.16.0.99

