---
- name: check if nohttpreferercheck exists
  ansible.builtin.shell: |
    cat /conf/config.yml | grep '<nohttpreferercheck>' | wc -l
  register: res

- name: add nohttpreferercheck
  ansible.builtin.lineinfile:
    path: /conf/config.xml
    line: '      <nohttpreferercheck>1</nohttpreferercheck>'
    state: present
    insertbefore: '</webgui>'
  when: res.stdout.strip() == "0"

- name: restart configd
  ansible.builtin.shell: |
    service configd restart

